---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ORGANIZATION_ID}}-mail-roundcube-nginx-config
data:
  default.conf: |
    server {
        listen 80 default_server;
        server_name _;
        root /var/www/html;

        resolver kube-dns.kube-system.svc.cluster.local valid=10s;

        location / {
            try_files $uri /index.php$is_args$args;
        }

        # Fixes Nginx removing the info sent by Keycloak to Roundcube
        # @see https://www.roundcubeforum.net/index.php?topic=29984.0
        # @see https://github.com/roundcube/roundcubemail/issues/8191
        #
        location ~ \.php(?:$|/) {
            fastcgi_split_path_info ^(.+\.php)(.*)$;

            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO       $fastcgi_path_info;

            fastcgi_pass {{ORGANIZATION_ID}}-mail-roundcube-app.default.svc.cluster.local:9000;
        }

        # Previous configuration (before Keycloak-Roundcube fix)
        #
        # location ~ \.php(/|$) {
        #     try_files $uri =404;
        #     fastcgi_pass {{ORGANIZATION_ID}}-mail-roundcube-app.default.svc.cluster.local:9000;
        #     fastcgi_read_timeout 300;
        #     proxy_read_timeout 300;
        #     fastcgi_split_path_info ^(.+\.php)(/.*)$;
        #     include fastcgi_params;
        #     fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        #     fastcgi_param DOCUMENT_ROOT $realpath_root;
        #     fastcgi_param PATH_INFO       $fastcgi_path_info;
        #     internal;
        # }

        client_max_body_size 6m;

        # Disable log files, error and logs will go to stdout/stderr
        # error_log  /var/log/nginx/error.log;
        # access_log /var/log/nginx/access.log;
    }

  zzz_roundcube-custom.ini: |
    ; Equivalent dans code php directement = date_default_timezone_set('Europe/Paris');
    date.timezone = Europe/Paris

