---
apiVersion: v1
kind: Service
metadata:
  name: {{ORGANIZATION_ID}}-mail-roundcube-nginx
  labels:
    service: {{ORGANIZATION_ID}}-mail-roundcube-nginx
spec:
  selector:
    service: {{ORGANIZATION_ID}}-mail-roundcube-nginx
  ports:
  - name: http
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ORGANIZATION_ID}}-mail-roundcube-nginx
  labels:
    service: {{ORGANIZATION_ID}}-mail-roundcube-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ORGANIZATION_ID}}-mail-roundcube-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: {{ORGANIZATION_ID}}-mail-roundcube-nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodepool
                operator: In
                values:
                - {{NODEPOOL}}
      containers:
      - name: {{ORGANIZATION_ID}}-mail-roundcube-nginx
        image: {{REGISTRY_URL}}/library/nginx:1.23.3-alpine
        imagePullPolicy: ""
        env:
        - name: NGINX_HOST
          value: localhost
        - name: NGINX_PHP_CGI
          value: {{ORGANIZATION_ID}}-mail-roundcube-app:9000
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www-data
          mountPath: /var/www/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: www-data
        hostPath:
          path: /mnt/data/{{ORGANIZATION_ID}}/mail/www_roundcube
          type: DirectoryOrCreate
      - name: nginx-config
        configMap:
          name: {{ORGANIZATION_ID}}-mail-roundcube-nginx-config
