---
apiVersion: v1
kind: Service
metadata:
  name: {{ORGANIZATION_ID}}-drive-onlyoffice-app
  labels:
    app: {{ORGANIZATION_ID}}-drive-onlyoffice-app
spec:
  selector:
    app: {{ORGANIZATION_ID}}-drive-onlyoffice-app
  ports:
  - name: http
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ORGANIZATION_ID}}-drive-onlyoffice-app
  labels:
    app: {{ORGANIZATION_ID}}-drive-onlyoffice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ORGANIZATION_ID}}-drive-onlyoffice-app
  template:
    metadata:
      labels:
        app: {{ORGANIZATION_ID}}-drive-onlyoffice-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodepool
                operator: In
                values:
                - {{NODEPOOL}}
      containers:
        - name: {{ORGANIZATION_ID}}-drive-onlyoffice-app
          image: {{REGISTRY_URL}}/onlyoffice/documentserver:7.5.0
          env:
            - name: JWT_SECRET
              value: "dFD64dfsvVCnds548CScdkh351Adcs65cd2v68smpBxwlJHb"
          ports:
            - name: http
              containerPort: 80