---
apiVersion: v1
kind: Service
metadata:
  name: {{ORGANIZATION_ID}}-extranet-wordpress-mariadb
  labels:
    app: {{ORGANIZATION_ID}}-extranet-wordpress-mariadb
spec:
  ports:
    - port: 3306
      name: mariadb
      protocol: TCP
  selector:
    app: {{ORGANIZATION_ID}}-extranet-wordpress-mariadb
    tier: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ORGANIZATION_ID}}-extranet-wordpress-mariadb
  labels:
    app: {{ORGANIZATION_ID}}-extranet-wordpress-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ORGANIZATION_ID}}-extranet-wordpress-mariadb
      tier: mariadb
  template:
    metadata:
      labels:
        app: {{ORGANIZATION_ID}}-extranet-wordpress-mariadb
        tier: mariadb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodepool
                operator: In
                values:
                - {{NODEPOOL}}
      containers:
      - image: {{REGISTRY_URL}}/library/mariadb:10.7.8
        name: mariadb
        env:
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ORGANIZATION_ID}}-extranet-wordpress-secrets
                key: mariadb-password
        ports:
          - containerPort: 3306
            name: mariadb
        volumeMounts:
          - name: {{ORGANIZATION_ID}}-extranet-wordpress-mariadb-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: {{ORGANIZATION_ID}}-extranet-wordpress-mariadb-persistent-storage
          hostPath:
            path: /mnt/data/{{ORGANIZATION_ID}}/extranet/mariadb
            type: DirectoryOrCreate