---
apiVersion: v1
kind: Service
metadata:
  name: {{ORGANIZATION_ID}}-mail-mailserver-app
  labels:
    app: {{ORGANIZATION_ID}}-mail-mailserver-app
spec:
  selector:
    app: {{ORGANIZATION_ID}}-mail-mailserver-app
  ports:
    # Transfer
    - name: transfer
      port: 25
      targetPort: 25
      protocol: TCP
    # ESMTP with implicit TLS
    - name: esmtp-implicit
      port: 465
      targetPort: 465
      protocol: TCP
    # ESMTP with explicit TLS (STARTTLS)
    - name: esmtp-explicit
      port: 587
      targetPort: 587
      protocol: TCP
    # IMAP
    - name: imap
      port: 143
      targetPort: 143
      protocol: TCP
    # IMAPS with implicit TLS
    - name: imap-implicit
      port: 993
      targetPort: 993
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ORGANIZATION_ID}}-mail-mailserver-app
  annotations:
    ignore-check.kube-linter.io/run-as-non-root: >-
      'mailserver' needs to run as root
    ignore-check.kube-linter.io/privileged-ports: >-
      'mailserver' needs privilegdes ports
    ignore-check.kube-linter.io/no-read-only-root-fs: >-
      There are too many files written to make the root FS read-only
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ORGANIZATION_ID}}-mail-mailserver-app
  template:
    metadata:
      labels:
        app: {{ORGANIZATION_ID}}-mail-mailserver-app
      annotations:
        container.apparmor.security.beta.kubernetes.io/mailserver: runtime/default
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodepool
                operator: In
                values:
                - {{NODEPOOL}}
      hostname: mail
      containers:
        - name: mailserver
          image: {{REGISTRY_URL}}/mailserver/docker-mailserver:11.3.1
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            privileged: false
            capabilities:
              add:
                # file permission capabilities
                - CHOWN
                - FOWNER
                - MKNOD
                - SETGID
                - SETUID
                - DAC_OVERRIDE
                # network capabilities
                - NET_ADMIN  # needed for F2B
                - NET_RAW    # needed for F2B
                - NET_BIND_SERVICE
                # miscellaneous  capabilities
                - SYS_CHROOT
                - KILL
              drop: [ALL]
            seccompProfile:
              type: RuntimeDefault

          # You want to tune this to your needs. If you disable ClamAV,
          #   you can use less RAM and CPU. This becomes important in
          #   case you're low on resources and Kubernetes refuses to
          #   schedule new pods.
          resources:
            limits:
              memory: 4Gi
              cpu: 1500m
            requests:
              memory: 2Gi
              cpu: 600m

          volumeMounts:
            # - name: files
            #   subPath: postfix-accounts.cf
            #   mountPath: /tmp/docker-mailserver/postfix-accounts.cf
            #   readOnly: true

            # configuration files
            # dms
            - name: config
              mountPath: /tmp/docker-mailserver
              subPath: dms
              readOnly: false
            # dovecot
            - name: config
              mountPath: /etc/dovecot/local.conf
              subPath: dovecot_conf_local.conf
              readOnly: true
            - name: config
              mountPath: /etc/dovecot/conf.d/10-auth.conf
              subPath: dovecot_conf_10auth.conf
              readOnly: false
            - name: config
              mountPath: /etc/dovecot/dovecot-oauth2.conf.ext
              subPath: dovecot_conf_oauth2.conf
              readOnly: false
            - name: config
              mountPath: /etc/dovecot/conf.d/auth-oauth2.inc
              subPath:  dovecot_auth_oauth2.conf
              readOnly: false
            # fail2ban
            - name: config
              mountPath: /etc/fail2ban/jail.local
              subPath:  fail2ban_jail_local.conf
              readOnly: false

            # persistent data
            - name: data
              mountPath: /var/mail
              subPath: data
              readOnly: false
            - name: data
              mountPath: /var/mail-state
              subPath: state
              readOnly: false
            - name: data
              mountPath: /var/log/mail
              subPath: log
              readOnly: false

            # # certificates
            # - name: certificates-rsa
            #   mountPath: /secrets/ssl/rsa/
            #   readOnly: true
            - name: certs
              mountPath: /tmp/docker-mailserver/ssl/

            # # other
            # - name: tmp-files
            #   mountPath: /tmp
            #   readOnly: false

          # ports:
          #   - name: transfer
          #     containerPort: 25
          #     protocol: TCP
          #   - name: esmtp-implicit
          #     containerPort: 465
          #     protocol: TCP
          #   - name: esmtp-explicit
          #     containerPort: 587
          #   - name: imap-implicit
          #     containerPort: 993
          #     protocol: TCP
          ports:
            - name: smtp
              containerPort: 25
              # hostPort: 25
            - name: esmtp-implicit
              containerPort: 465
              # hostPort: 465
            - name: smtp-auth
              containerPort: 587
              # hostPort: 587
            - name: imap
              containerPort: 143
              # hostPort: 143
            - name: imap-secure
              containerPort: 993
              # hostPort: 993

          envFrom:
            - configMapRef:
                name: {{ORGANIZATION_ID}}-mail-mailserver.environment

      restartPolicy: Always

      volumes:
        # # configuration files
        # - name: files
        #   configMap:
        #     name: mailserver.files
            
        # configuration
        - name: config
          hostPath:
            path: /mnt/data/{{ORGANIZATION_ID}}/mail/config_mailserver
            type: DirectoryOrCreate
            
        # persistent data
        - name: data
          hostPath:
            path: /mnt/data/{{ORGANIZATION_ID}}/mail/data_mailserver
            type: DirectoryOrCreate

        # # certificates
        # - name: certificates-rsa
        #   secret:
        #     secretName: mail-tls-certificate-rsa
        #     items:
        #       - key: tls.key
        #         path: tls.key
        #       - key: tls.crt
        #         path: tls.crt

        # certificates
        - name: certs
          secret:
            secretName: {{ORGANIZATION_ID}}-mail-mailserver-secrets
            items:
              - key: krisalee-key
                path: mail.krisalee.joona.fr-key.pem
                #
              - key: krisalee-cert
                path: mail.krisalee.joona.fr-cert.pem
                #
              - key: demo-ca-cert
                path: demoCA/cacert.pem

        # # other
        # - name: tmp-files
        #   emptyDir: {}
