---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ORGANIZATION_ID}}-mail-mailserver.environment
immutable: false
data:
  TLS_LEVEL: modern
  POSTSCREEN_ACTION: drop
  OVERRIDE_HOSTNAME: mail..joona.fr
  FAIL2BAN_BLOCKTYPE: drop
  POSTMASTER_ADDRESS: postmaster@.joona.fr
  UPDATE_CHECK_INTERVAL: 10d
  POSTFIX_INET_PROTOCOLS: ipv4
  ONE_DIR: '1'
  ENABLE_CLAMAV: '1'
  ENABLE_postgresqlY: '0'
  ENABLE_FAIL2BAN: '1'
  AMAVIS_LOGLEVEL: '-1'
  SPOOF_PROTECTION: '1'
  MOVE_SPAM_TO_JUNK: '1'
  ENABLE_UPDATE_CHECK: '1'
  ENABLE_SPAMASSASSIN: '1'
  SUPERVISOR_LOGLEVEL: warn
  SPAMASSASSIN_SPAM_TO_INBOX: '1'

  # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/ssl
  SSL_TYPE: self-signed
  # SSL_CERT_PATH: /secrets/ssl/rsa/tls.crt
  # SSL_KEY_PATH: /secrets/ssl/rsa/tls.key
# ---
# apiVersion: v1
# kind: ConfigMap

# metadata:
#   name: mailserver.files

# data:
#   postfix-accounts.cf: |
#     test@example.com|{SHA512-CRYPT}$6$someHashValueHere
#     other@example.com|{SHA512-CRYPT}$6$someOtherHashValueHere