# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate

# metadata:
#   name: mail-tls-certificate-rsa

# spec:
#   secretName: mail-tls-certificate-rsa
#   isCA: false
#   privateKey:
#     algorithm: RSA
#     encoding: PKCS1
#     size: 2048
#   dnsNames: [mail.submanta.com]
#   issuerRef:
#     name: mail-issuer
#     kind: Issuer
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ORGANIZATION_ID}}-mail-mailserver-secrets
stringData:
  krisalee-key:
  krisalee-cert:
  demo-ca-cert:
#