---
apiVersion: v1
kind: Service
metadata:
  name: {{ORGANIZATION_ID}}-auth-krisalee-user-management-app
  labels:
    app: {{ORGANIZATION_ID}}-auth-krisalee-user-management-app
spec:
  selector:
    app: {{ORGANIZATION_ID}}-auth-krisalee-user-management-app
  ports:
    - name: http
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ORGANIZATION_ID}}-auth-krisalee-user-management-app
  labels:
    app: {{ORGANIZATION_ID}}-auth-krisalee-user-management-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ORGANIZATION_ID}}-auth-krisalee-user-management-app
  template:
    metadata:
      labels:
        app: {{ORGANIZATION_ID}}-auth-krisalee-user-management-app
    spec:
      serviceAccountName: registry-custom-image
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodepool
                    operator: In
                    values:
                      - {{NODEPOOL}}
      containers:
        - name: {{ORGANIZATION_ID}}-auth-krisalee-user-management-app
          image: {{REGISTRY_CUSTOM_IMAGE_URL}}/krisalee-user-management-front:1.0.0
          # args: ['start-dev']
          # env:
          #   - name: krisalee-user-management_orgid
          #     value: {{ORGANIZATION_ID}}
          # volumeMounts:
          # - mountPath: /opt/krisalee-user-management/providers
          #   name: krisalee-user-management-providers-volume
      # volumes:
      # - name: krisalee-user-management-providers-volume
      #   hostPath:
      #     path: /mnt/data/{{ORGANIZATION_ID}}/auth/krisalee-user-management/providers
      #     type: DirectoryOrCreate