---
apiVersion: v1
kind: Service
metadata:
 name: load-balancer
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
    nodePort: 30216
  - port: 443
    name: https
    protocol: TCP
    targetPort: 443
    nodePort: 30217
  selector:
      app: krisalee-frontal-nginx-app
  type: LoadBalancer
  externalTrafficPolicy: Local