---
apiVersion: v1
kind: Service
metadata:
  name: {{ORGANIZATION_ID}}-chat-rocketchat-app
  labels:
    app: {{ORGANIZATION_ID}}-chat-rocketchat-app
spec:
  selector:
    app: {{ORGANIZATION_ID}}-chat-rocketchat-app
  ports:
  - name: http
    port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ORGANIZATION_ID}}-chat-rocketchat-app
  labels:
    app: {{ORGANIZATION_ID}}-chat-rocketchat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ORGANIZATION_ID}}-chat-rocketchat-app
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ORGANIZATION_ID}}-chat-rocketchat-app
        tier: frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodepool
                operator: In
                values:
                - {{NODEPOOL}}
      containers:
      - image: registry.rocket.chat/rocketchat/rocket.chat:6.4.8
        name: rocketchat
        env:
        #- name: INITIAL_USER
          #value: "yes" #Ne fonctionne pas...
        #- name: ADMIN_USERNAME
          #value: "apitech" #ne pas utiliser 'admin' nom interdit
        #- name: ADMIN_NAME
          #value: "apitech"
        #- name: ADMIN_PASS
          #value: ""
        #- name: ADMIN_EMAIL
          #value: "sysadmin@apitech.fr"
        #- name: OVERWRITE_SETTING_Show_Setup_Wizard
          #value: "completed"
        #- name: REG_TOKEN
          #value: "" #${REG_TOKEN}
        #- name: MAIL_URL
          #value: "" #smtp://smtp.email
        #- name: Accounts_UseDNSDomainCheck
          #value: "False"
        #- name: Accounts_SetDefaultAvatar
          #value: "False"
        # - name: ROOT_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: {{ORGANIZATION_ID}}-chat-rocketchat-secrets
        #       key: root-url
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: {{ORGANIZATION_ID}}-chat-rocketchat-secrets
              key: mongodb-url
        - name: MONGO_OPLOG_URL
          valueFrom:
            secretKeyRef:
              name: {{ORGANIZATION_ID}}-chat-rocketchat-secrets
              key: mongodb-oplog-url
        ports:
        - containerPort: 3000
          name: rocketchat
