---
apiVersion: v1
kind: Secret
metadata:
  name: {{ORGANIZATION_ID}}-chat-rocketchat-secrets
type: Opaque
stringData:
  mongodb-user: rocketchat
  mongodb-password: 123456
  mongodb-db: rocketchat
  mongodb-url: mongodb://rocketchat:123456@{{ORGANIZATION_ID}}-chat-rocketchat-mongodb:27017/rocketchat
  mongodb-oplog-url: mongodb://{{ORGANIZATION_ID}}-chat-rocketchat-mongodb:27017/local?replSet=rs0
  #root-url: https://chat.krisalee.dev.joona.fr